# Generated by Django 3.0.4 on 2020-07-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='routeros_router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('hostname', models.CharField(default='', max_length=100)),
                ('port_cmd', models.CharField(default='', max_length=100)),
                ('ospf', models.CharField(default='', max_length=100)),
                ('inter_vlan', models.CharField(default='', max_length=100)),
                ('ip_add_vlan', models.CharField(default='', max_length=100)),
                ('port_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Automation.devices')),
            ],
        ),
        migrations.CreateModel(
            name='ce_switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('hostname', models.CharField(default='', max_length=100)),
                ('vlan', models.CharField(default='', max_length=100)),
                ('port_ip', models.CharField(default='', max_length=100)),
                ('port_vlan', models.CharField(default='', max_length=100)),
                ('port_cmd1', models.CharField(default='', max_length=100)),
                ('port_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Automation.devices')),
            ],
        ),
    ]
