# Generated by Django 3.0.4 on 2020-07-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0002_ce_switch_routeros_router'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='target',
        ),
        migrations.AddField(
            model_name='log',
            name='targetss',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='messages',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.CharField(default='', max_length=255),
        ),
    ]
