# Generated by Django 3.0.4 on 2020-07-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0003_auto_20200706_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='account',
            field=models.CharField(default='', max_length=255),
        ),
    ]
