# Generated by Django 3.0.4 on 2020-07-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0004_log_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='mac_os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oui', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
            ],
        ),
    ]
