# Generated by Django 3.0.4 on 2020-07-27 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0007_auto_20200727_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iosrouter',
            old_name='ospf',
            new_name='ospf_mask',
        ),
        migrations.RenameField(
            model_name='iosrouter',
            old_name='ospf2',
            new_name='ospf_mask2',
        ),
        migrations.RenameField(
            model_name='iosrouter',
            old_name='ospf3',
            new_name='ospf_mask3',
        ),
    ]
