# Generated by Django 3.0.4 on 2020-07-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0008_auto_20200727_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='iosrouter',
            name='i_vlan_mask',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='iosrouter',
            name='i_vlan_mask2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='iosrouter',
            name='port_mask',
            field=models.CharField(default='', max_length=100),
        ),
    ]
