# Generated by Django 3.0.4 on 2020-07-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0009_auto_20200728_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ios_switch',
            old_name='port_cmd',
            new_name='interface',
        ),
        migrations.RenameField(
            model_name='ios_switch',
            old_name='port_ip',
            new_name='interface2',
        ),
        migrations.AddField(
            model_name='ios_switch',
            name='mac',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ios_switch',
            name='mode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ios_switch',
            name='mode2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ios_switch',
            name='vlan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ios_switch',
            name='vlan2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ios_switch',
            name='vlan_id2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ios_switch',
            name='vlan_name2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='iosrouter',
            name='default_gateway',
            field=models.CharField(default='', max_length=100),
        ),
    ]
