# Generated by Django 3.0.4 on 2020-07-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0010_auto_20200728_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='ios_switch',
            name='gateway',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ios_switch',
            name='vlan_id3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ios_switch',
            name='vlan_name3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
