# Generated by Django 3.0.4 on 2020-08-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0011_auto_20200729_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='switchservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namefile', models.CharField(default='', max_length=100)),
                ('vlan_id', models.CharField(default='', max_length=100)),
                ('vlan_name', models.CharField(default='', max_length=100)),
                ('vlan_id2', models.CharField(default='', max_length=100)),
                ('vlan_name2', models.CharField(default='', max_length=100)),
                ('vlan_id3', models.CharField(default='', max_length=100)),
                ('vlan_name3', models.CharField(default='', max_length=100)),
                ('interface', models.CharField(default='', max_length=100)),
                ('mode', models.CharField(default='', max_length=100)),
                ('vlan', models.CharField(default='', max_length=100)),
                ('interface2', models.CharField(default='', max_length=100)),
                ('mode2', models.CharField(default='', max_length=100)),
                ('vlan2', models.CharField(default='', max_length=100)),
                ('interface3', models.CharField(default='', max_length=100)),
                ('mode3', models.CharField(default='', max_length=100)),
                ('vlan3', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ios_switch',
            name='interface3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ios_switch',
            name='mode3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ios_switch',
            name='vlan3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
