# Generated by Django 3.0.4 on 2020-03-19 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleAWSGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ansible_connection', models.CharField(choices=[('network_cli', 'network_cli'), ('paramiko_ssh', 'paramiko'), ('chroot', 'chroot'), ('docker', 'docker'), ('httpapi', 'httpapi'), ('netconf', 'netconf'), ('winrm', 'winrm')], max_length=100)),
                ('ami', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('sshkey', models.CharField(max_length=100)),
                ('vpcid', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ansible_aws_groups',
            },
        ),
        migrations.CreateModel(
            name='AnsibleNetworkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ansible_connection', models.CharField(choices=[('network_cli', 'network_cli'), ('paramiko_ssh', 'paramiko'), ('chroot', 'chroot'), ('docker', 'docker'), ('httpapi', 'httpapi'), ('netconf', 'netconf'), ('winrm', 'winrm')], max_length=100)),
                ('ansible_become', models.BooleanField(default=False)),
                ('ansible_network_os', models.CharField(choices=[('a10', 'a10'), ('aci', 'aci'), ('aireos', 'aireos'), ('aos', 'aos'), ('aruba', 'aruba'), ('asa', 'asa'), ('f5', 'f5'), ('ios', 'ios'), ('iosxr', 'iosxr'), ('nxos', 'nxos')], max_length=100)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_group', to='djansible.AnsibleNetworkGroup')),
            ],
            options={
                'db_table': 'ansible_network_groups',
            },
        ),
        migrations.CreateModel(
            name='AnsibleServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ansible_connection', models.CharField(choices=[('network_cli', 'network_cli'), ('paramiko_ssh', 'paramiko'), ('chroot', 'chroot'), ('docker', 'docker'), ('httpapi', 'httpapi'), ('netconf', 'netconf'), ('winrm', 'winrm')], max_length=100)),
                ('ansible_become', models.BooleanField(default=False)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_group', to='djansible.AnsibleServerGroup')),
            ],
            options={
                'db_table': 'ansible_server_groups',
            },
        ),
        migrations.CreateModel(
            name='AnsibleServerHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('ansible_ssh_host', models.GenericIPAddressField()),
                ('ansible_user', models.CharField(max_length=100)),
                ('ansible_ssh_pass', models.CharField(max_length=100)),
                ('ansible_become_pass', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djansible.AnsibleServerGroup')),
            ],
            options={
                'db_table': 'ansible_server_hosts',
            },
        ),
        migrations.CreateModel(
            name='AnsibleNetworkHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('ansible_ssh_host', models.GenericIPAddressField()),
                ('ansible_user', models.CharField(max_length=100)),
                ('ansible_ssh_pass', models.CharField(max_length=100)),
                ('ansible_become_pass', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djansible.AnsibleNetworkGroup')),
            ],
            options={
                'db_table': 'ansible_network_hosts',
            },
        ),
    ]
