# Generated by Django 3.0.4 on 2020-03-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djansible', '0002_action_actions_book_playbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='task',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
