# Generated by Django 3.0.4 on 2020-03-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djansible', '0003_auto_20200326_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbook',
            name='task',
        ),
        migrations.DeleteModel(
            name='Actions',
        ),
        migrations.DeleteModel(
            name='PlayBook',
        ),
    ]
