# Generated by Django 3.0.4 on 2020-03-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djansible', '0004_auto_20200326_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('commands', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'action',
            },
        ),
        migrations.CreateModel(
            name='PlayBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansible_connection', models.CharField(choices=[('network_cli', 'network_cli'), ('paramiko_ssh', 'paramiko'), ('chroot', 'chroot'), ('docker', 'docker'), ('httpapi', 'httpapi'), ('netconf', 'netconf'), ('winrm', 'winrm')], max_length=100)),
                ('ansible_become', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('hosts', models.CharField(max_length=100)),
                ('become', models.CharField(max_length=100)),
                ('become_method', models.CharField(max_length=100)),
                ('gather_facts', models.CharField(max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djansible.Actions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
