# Generated by Django 3.0.4 on 2020-03-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djansible', '0005_actions_playbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayBook',
        ),
    ]
