# Generated by Django 3.0.4 on 2020-03-27 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djansible', '0006_delete_playbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hosts', models.CharField(max_length=100)),
                ('become', models.CharField(max_length=100)),
                ('become_method', models.CharField(max_length=100)),
                ('gather_facts', models.CharField(max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djansible.Actions')),
            ],
        ),
    ]
