# Generated by Django 3.0.4 on 2020-03-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djansible', '0007_playbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hosts', models.CharField(max_length=100)),
                ('become', models.CharField(max_length=100)),
                ('become_method', models.CharField(max_length=100)),
                ('gather_facts', models.CharField(max_length=100)),
                ('task', models.ManyToManyField(to='djansible.Actions')),
            ],
        ),
    ]
