# Generated by Django 3.0.4 on 2020-04-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djansible', '0008_playbooks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnsibleAWSGroup',
        ),
        migrations.RemoveField(
            model_name='ansiblenetworkgroup',
            name='parent_group',
        ),
        migrations.RemoveField(
            model_name='ansiblenetworkhost',
            name='group',
        ),
        migrations.RemoveField(
            model_name='ansibleservergroup',
            name='parent_group',
        ),
        migrations.RemoveField(
            model_name='ansibleserverhost',
            name='group',
        ),
        migrations.RemoveField(
            model_name='playbook',
            name='task',
        ),
        migrations.RemoveField(
            model_name='playbooks',
            name='task',
        ),
        migrations.DeleteModel(
            name='Actions',
        ),
        migrations.DeleteModel(
            name='AnsibleNetworkGroup',
        ),
        migrations.DeleteModel(
            name='AnsibleNetworkHost',
        ),
        migrations.DeleteModel(
            name='AnsibleServerGroup',
        ),
        migrations.DeleteModel(
            name='AnsibleServerHost',
        ),
        migrations.DeleteModel(
            name='PlayBook',
        ),
        migrations.DeleteModel(
            name='PlayBooks',
        ),
    ]
